[workspace]
members = ["crates/core", "crates/cli", "crates/desktop"]
default-members = ["crates/core", "crates/cli"]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2024"
license = "GPL-3.0-only"

[workspace.dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
syncandrun-core = { path = "crates/core" }

[profile.dev]
debug = 0

[profile.test]
debug = 0
